CREATE TABLE messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  text TEXT NOT NULL,
  sender VARCHAR(50) NOT NULL,
  user VARCHAR(50) NOT NULL,
  time TIME NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
